name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_LEVEL: 30                   # Change this to your target API level
      TARGET: google_apis              # Use google_apis or google_apis_playstore
      ABI: x86_64                      # x86_64 is generally preferred for CI
      EMULATOR_NAME: test_emulator

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Java (required for Android SDK)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    # Step 3: Set up the Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ env.API_LEVEL }}
        target: ${{ env.TARGET }}
        arch: ${{ env.ABI }}
        profile: 'default'
        emulator-name: ${{ env.EMULATOR_NAME }}
        force-create: true    # Ensures a fresh emulator instance
        disable-animations: true

    # Step 4: Start the emulator
    - name: Start emulator
      run: |
        adb start-server
        emulator -avd $EMULATOR_NAME -no-snapshot -no-window -gpu swiftshader_indirect -no-boot-anim &
        adb wait-for-device
        adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
        adb shell input keyevent 82  # Unlocks the emulator screen

    # Step 5: Install dependencies and build the project
    - name: Install dependencies and build
      run: |
        ./gradlew assembleDebug

    # Step 6: Run tests on the emulator
    - name: Run UI tests
      run: |
        ./gradlew connectedAndroidTest

    # Step 7: Stop the emulator
    - name: Stop emulator
      run: |
        adb emu kill
