name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_LEVEL: 30
      TARGET: google_apis
      ABI: x86_64
      EMULATOR_NAME: test_emulator

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          target: ${{ env.TARGET }}
          arch: ${{ env.ABI }}
          emulator-name: ${{ env.EMULATOR_NAME }}
          force-create: true
          disable-animations: true

      - name: Add Android SDK tools to PATH
        run: |
          export ANDROID_HOME=$HOME/android/sdk
          export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/tools/bin
          mkdir -p $ANDROID_HOME


