name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_LEVEL: 30
      TARGET: google_apis
      ABI: x86_64
      EMULATOR_NAME: test_emulator

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          target: ${{ env.TARGET }}
          arch: ${{ env.ABI }}
          emulator-name: ${{ env.EMULATOR_NAME }}
          force-create: true
          disable-animations: true

      - name: Add Android SDK tools to PATH
        run: |
          export ANDROID_HOME=$HOME/android/sdk
          export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/tools/bin
          mkdir -p $ANDROID_HOME

      - name: Start emulator
        run: |
          adb start-server
          $ANDROID_HOME/emulator/emulator -avd -list-avds
          $ANDROID_HOME/emulator/emulator -avd $EMULATOR_NAME -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim &
          adb wait-for-device
          boot_completed=""
          timeout=600
          while [[ -z "$boot_completed" && $timeout -gt 0 ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            if [[ "$boot_completed" != "1" ]]; then
              sleep 5
              timeout=$((timeout - 5))
            fi
          done
          if [[ "$boot_completed" != "1" ]]; then
            echo "Emulator failed to boot within the timeout period."
            exit 1
          fi
      - name: Build and run tests
        run: |
          ./gradlew assembleDebug
          ./gradlew connectedAndroidTest

      - name: Stop emulator
        run: adb emu kill


